name: flutter_starter_kit
description: "A production-ready Flutter starter kit"
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

  flutter_bloc: ^9.1.1
  go_router: ^17.1.0
  equatable: ^2.0.8

  #DB

  #DI
  get_it: ^9.2.0
  injectable: ^2.6.0

  #Cache
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  flutter_secure_storage: ^10.0.0


  #Network
  dio: ^5.9.1
  envied: ^1.3.2
#  json_annotation: ^4.9.0
  #higher version crash in pod
  connectivity_plus: ^7.0.0
  pretty_dio_logger: ^1.3.1

  #Localizations
  flutter_phoenix: ^1.1.1
  easy_localization: ^3.0.8

  #Utilities
  intl: ^0.20.2
  logger: ^2.6.2
  async: ^2.13.0
  share_plus: ^12.0.1
  url_launcher: ^6.3.0
  in_app_review: ^2.0.8
  flutter_local_notifications: ^20.0.0
  flutter_web_browser: ^0.17.1
  flutter_screenutil: ^5.9.3
  device_info_plus: ^12.3.0
  sensors_plus: ^7.0.0

  #PIN UI
  pinput: ^6.0.2

  #UI
  flutter_svg: ^2.0.11
  auto_size_text: ^3.0.0
  device_preview: ^1.2.0
  loading_indicator: ^3.1.1
  shimmer_animation: ^2.1.0+1
  flutter_chat_bubble: ^2.0.2
  cached_network_image: ^3.3.1
  intl_phone_number_input: ^0.7.4



dev_dependencies:
  flutter_test:
    sdk: flutter

  mockito: ^5.6.1
  hive_ce_test: ^2.0.0
  flutter_lints: ^6.0.0
  build_runner: ^2.10.4
  envied_generator: ^1.3.2
  json_serializable: ^6.11.3
  hive_ce_generator: ^1.11.0
  injectable_generator: ^2.7.1+4


flutter:
  uses-material-design: true

  assets:
    - assets/translations/

    - assets/
    - assets/fonts/
    - assets/icons/
    - assets/icons/common/
    - assets/images/
    - assets/translations/

#  fonts:
#    - family: Cairo
#      fonts:
#        - asset: assets/fonts/cairo/Cairo-Black.ttf
#          weight: 900
#        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
#          weight: 800
#        - asset: assets/fonts/cairo/Cairo-Bold.ttf
#          weight: 700
#        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
#          weight: 600
#        - asset: assets/fonts/cairo/Cairo-Medium.ttf
#          weight: 500
#        - asset: assets/fonts/cairo/Cairo-Regular.ttf
#          weight: 400
#        - asset: assets/fonts/cairo/Cairo-Light.ttf
#          weight: 300
#        - asset: assets/fonts/cairo/Cairo-ExtraLight.ttf
#          weight: 200


  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
